name: Deploy microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Debug Secrets
        run: |
          if [[ -z "${DOCKER_HUB_USERNAME}" ]]; then
            echo "DOCKER_HUB_USERNAME is empty or not set"
          else
            echo "DOCKER_HUB_USERNAME is set (value masked)"
          fi
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_HUB_USERNAME }} | docker login --username ${{ secrets.DOCKER_HUB_PASSWORD }} --password-stdin
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/microservices:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/microservices:latest

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra/terraform

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name microservice-eks --region eu-west-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
